OPTION: "debug"
PRETRAINED: True
COPY_RGB_WEIGHTS: False
TARGET_SIZE: [112, 112]
BODYPARTS_DIR: "bodyparts_split"
DEPTHMAPS_DIR: "depth_maps"
AUGMENTATIONS: [hflip, crop]
STRATIFIED: True  # feeding more touch class (underrepresented) to balance
LOSS_WEIGHTS: [1, 1]  # keep these the same if stratified is True
LR: 0.001
BATCH_SIZE: 32
EPOCHS: 15