OPTION: "jointmaps_rgb_bodyparts"
PRETRAINED: True
COPY_RGB_WEIGHTS: False
TARGET_SIZE: [112, 112]
BODYPARTS_DIR: "bodyparts_split"
DEPTHMAPS_DIR: "depth_maps"
AUGMENTATIONS: [hflip, crop]
SEGMENTATION: False  # True: 21 + 21 dimensional labels, False: 21 * 21 dimensional labels
LR: 0.001
BATCH_SIZE: 32
EPOCHS: 15