OPTION: "jointmaps_bodyparts"
BACKBONE: "resnet50"
PRETRAINED: False
COPY_RGB_WEIGHTS: False
TARGET_SIZE: [112, 112]
BODYPARTS_DIR: "bodyparts_split"
DEPTHMAPS_DIR: "depth_maps"
AUGMENTATIONS: [hflip, crop]
MULTITASK: True  # True: (21 + 21, 21 * 21) dimensional labels, False: 21 + 21 dimensional labels
LR: 0.1
BATCH_SIZE: 32
EPOCHS: 50
LOSS_WEIGHTS: [0, 0.5, 0, 0.5]  # 42 12 21*21 6*6
